version: '3'

services:
  elrond:
    build:
      context: docker/elrond

    command: bash -c "go run cmd/bootnode/main.go -port 4000 -max-allowed-peers 4 -private-key \"ZBis8aK5I66x1hwD+fE8sIw2nwQR5EBlTM8EiAOLZwE=\""
    ports:
      - 8080:8080
  filebeat:
    build: docker/filebeat
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      LOGSTASH_PORT: ${LOGSTASH_PORT}
      INDEX: ${ELASTIC_INDEX}
    volumes:
    - ./docker/filebeat/filebeat.yml:/filebeat.yml
    - ./docker/filebeat/logstash-beats.crt:/etc/pki/tls/certs/logstash-beats.crt
    - ${ELROND_LOG_LOCATION}:/elogs