version: '3'

services:
  elrond:
    build:
      context: ./
      dockerfile: ./docker/elrond/Dockerfile

    command: bash -c "go run cmd/bootnode/main.go -port 4000 -max-allowed-peers 4 -private-key \"ZBis8aK5I66x1hwD+fE8sIw2nwQR5EBlTM8EiAOLZwE=\""
    ports:
      - 8080:8080
  elrond2:
    build:
      context: ./
      dockerfile: ./docker/elrond/Dockerfile

    command: bash -c "go run cmd/bootnode/main.go -port 4001 -max-allowed-peers 4 -private-key \"unkVM1J1JvlNFqY3uo/CvAay6BsIL3IzDH9GDgmfUAA=\""
    ports:
      - 8081:8080
  elrond3:
    build:
      context: ./
      dockerfile: ./docker/elrond/Dockerfile

    command: bash -c "go run cmd/bootnode/main.go -port 4002 -max-allowed-peers 4 -private-key \"Or0C7+gvlr/kIZLS+tiBBQfbUQ+pqS9FTE3dXfs5Swg=\""
    ports:
      - 8082:8080
  filebeat:
    build: docker/filebeat
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      LOGSTASH_PORT: ${LOGSTASH_PORT}
      INDEX: ${ELASTIC_INDEX}
    volumes:
    - ./docker/filebeat/filebeat.yml:/filebeat.yml
    - ./docker/filebeat/logstash-beats.crt:/etc/pki/tls/certs/logstash-beats.crt
    - ${ELROND_LOG_LOCATION}:/elogs