version: '3'

services:
  filebeat:
    build: docker/filebeat
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      LOGSTASH_PORT: 5044
      INDEX: logstash
    volumes:
    - ./docker/filebeat/filebeat.yml:/filebeat.yml
    - ./docker/filebeat/logstash-beats.crt:/etc/pki/tls/certs/logstash-beats.crt
    - ~/Library/Elrond/logs:/elogs