# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/360EntSecGroup-Skylar/excelize"
  version = "1.4.0"

[[constraint]]
  name = "github.com/beevik/ntp"
  version = "0.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/btcd"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/btcutil"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.1"

[[constraint]]
  name = "github.com/gin-contrib/cors"
  version = "1.2.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/glycerine/go-capnproto"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "1.1.1"

[[constraint]]
  name = "github.com/hashicorp/golang-lru"
  version = "0.5.0"

[[constraint]]
  name = "github.com/ipfs/go-ipfs-addr"
  version = "v0.0.1"

[[constraint]]
  name = "github.com/libp2p/go-conn-security-multistream"
  version = "v0.0.1"

[[constraint]]
  name = "github.com/libp2p/go-libp2p"
  version = "v0.0.2"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-crypto"
  version = "v0.0.1"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-host"
  version = "v0.0.1"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-metrics"
  version = "v0.0.1"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-net"
  version = "v0.0.1"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-peer"
  version = "v0.0.1"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-peerstore"
  version = "v0.0.1"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-protocol"
  version = "v0.0.1"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-pubsub"
  version = "v0.0.1"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-secio"
  version = "v0.0.1"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-swarm"
  version = "v0.0.1"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-transport-upgrader"
  version = "v0.0.1"

[[constraint]]
  name = "github.com/libp2p/go-tcp-transport"
  version = "v0.0.1"

[[constraint]]
  name = "github.com/libp2p/go-testutil"
  version = "v0.0.1"

[[constraint]]
  name = "github.com/multiformats/go-multiaddr"
  version = "v0.0.2"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.2.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  branch = "master"
  name = "github.com/syndtr/goleveldb"

[[constraint]]
  name = "github.com/whyrusleeping/go-smux-multistream"
  version = "v2.0.2"

[[constraint]]
  name = "github.com/whyrusleeping/go-smux-yamux"
  version = "v2.0.9"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/dedis/kyber.v2"

[[constraint]]
  name = "gotest.tools"
  version = "2.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/cornelk/hashmap"

[prune]
  go-tests = true
  unused-packages = true
