# GeneralSettings section of the node
[GeneralSettings]
   # DestinationShardAsObserver represents the desired shard when running as observer
   # value will be given as string. For example: "0", "1", "15", "metachain"
   DestinationShardAsObserver = "0"

[MiniBlocksStorage]
    [MiniBlocksStorage.Cache]
        Size = 1000
        Type = "LRU"
    [MiniBlocksStorage.DB]
        FilePath = "MiniBlocks"
        Type = "LvlDB"

[PeerBlockBodyStorage]
    [PeerBlockBodyStorage.Cache]
        Size = 100
        Type = "LRU"
    [PeerBlockBodyStorage.DB]
        FilePath = "PeerBlocks"
        Type = "LvlDB"

[BlockHeaderStorage]
    [BlockHeaderStorage.Cache]
        Size = 100
        Type = "LRU"
    [BlockHeaderStorage.DB]
        FilePath = "BlockHeaders"
        Type = "LvlDB"

[ShardDataStorage]
    [ShardDataStorage.Cache]
        Size = 1000
        Type = "LRU"
    [ShardDataStorage.DB]
        FilePath = "ShardData"
        Type = "LvlDB"

[PeerDataStorage]
    [PeerDataStorage.Cache]
        Size = 100
        Type = "LRU"
    [PeerDataStorage.DB]
        FilePath = "PeerData"
        Type = "LvlDB"

[MetaBlockStorage]
    [MetaBlockStorage.Cache]
        Size = 100
        Type = "LRU"
    [MetaBlockStorage.DB]
        FilePath = "MetaBlock"
        Type = "LvlDB"

[TxStorage]
    [TxStorage.Cache]
        Size = 100000
        Type = "LRU"
    [TxStorage.DB]
        FilePath = "Transactions"
        Type = "LvlDB"

[AccountsTrieStorage]
    [AccountsTrieStorage.Cache]
        Size = 100000
        Type = "LRU"
    [AccountsTrieStorage.DB]
        FilePath = "AccountsTrie"
        Type = "LvlDB"
    [AccountsTrieStorage.Bloom]
        Size = 2048
        HashFunc = ["Keccak", "Blake2b", "Fnv"]

[BadBlocksCache]
    Size = 100
    Type = "LRU"

[TxBlockBodyDataPool]
    Size = 100
    Type = "LRU"

[StateBlockBodyDataPool]
    Size = 100
    Type = "LRU"

[PeerBlockBodyDataPool]
    Size = 10000
    Type = "LRU"

[BlockHeaderDataPool]
    Size = 10000
    Type = "LRU"

[BlockHeaderNoncesDataPool]
    Size = 100000
    Type = "LRU"

[MetaHeaderNoncesDataPool]
    Size = 100000
    Type = "FIFOSharded"
    Shards = 100

[TxDataPool]
    Size = 100000
    Type = "FIFOSharded"
    Shards = 100

[ShardHeadersDataPool]
    Size = 10000
    Type = "FIFOSharded"
    Shards = 100

[MiniBlockHeaderHashesDataPool]
    Size = 10000
    Type = "FIFOSharded"
    Shards = 100

[MetaBlockBodyDataPool]
    Size = 1000
    Type = "LRU"

[Logger]
    Path = "logs"
    StackTraceDepth = 2

[Address]
    Length = 32
    Prefix = "0x"

[Hasher]
   Type = "blake2b"

[MultisigHasher]
   Type = "blake2b"

[Marshalizer]
   Type = "json"

# ResourceStats, if enabled, will output in a folder called "stats"
# resource statistics. For example: number of active go routines, memory allocation, number of GC sweeps, etc.
# RefreshIntervalInSec will tell how often a new line containing stats should be added in stats file
[ResourceStats]
   Enabled = true
   RefreshIntervalInSec = 30

# Heartbeat, if enabled, will output a heartbeat singal once x seconds,
# where x in [MinTimeToWaitBetweenBroadcastsInSec, MaxTimeToWaitBetweenBroadcastsInSec)
[Heartbeat]
   Enabled = true
   MinTimeToWaitBetweenBroadcastsInSec = 20
   MaxTimeToWaitBetweenBroadcastsInSec = 25
   DurationInSecToConsiderUnresponsive = 60

# Consensus type which will be used (the current implementation can manage "bn" and "bls")
# When consensus type is "bls" the multisig hasher type should be "blake2b"
[Consensus]
   Type = "bls"
