#Econimics config of the node
[EconomicsAddresses]
    CommunityAddress = "1bedf9f1db526aa98eb61f251e6eb29df64c0a4d96261b6fe9d4df1bc2cf5420"
    BurnAddress = "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef"

[RewardsSettings]
    RewardsValue = "2000"
    CommunityPercentage = 0.10
    LeaderPercentage = 0.50
    BurnPercentage = 0.40	

[FeeSettings]
    MinGasPrice = "10"
    MinGasLimit = "100"
