#Econimics config of the node
[EconomicsAddresses]
    CommunityAddress = "1bedf9f1db526aa98eb61f251e6eb29df64c0a4d96261b6fe9d4df1bc2cf5420"
    BurnAddress = "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef"

[RewardsSettings]
    RewardsValue = "1000"
    CommunityPercentage = 0.10
    LeaderPercentage = 0.50
    BurnPercentage = 0.40
    DenominationCoefficientForView = "0.0001"

[FeeSettings]
    MinGasPrice = "0"
    MinGasLimit = "5"

[ValidatorSettings]
    StakeValue = "500000000000000000000000"
    UnBoundPeriod = "100000"

[RatingSettings]
    StartRating = 50
    MaxRating = 100
	MinRating = 0
		[[RatingSettings.RatingValue]]
    	name = "ValidatorIncreaseRatingStep"
    	value = 1
    	[[RatingSettings.RatingValue]]
    	name = "ValidatorDecreaseRatingStep"
    	value = -2
    	[[RatingSettings.RatingValue]]
    	name = "ProposerIncreaseRatingStep"
    	value = 2
    	[[RatingSettings.RatingValue]]
    	name = "ProposerDecreaseRatingStep"
    	value = -4
