#Econimics config of the node
[GlobalSettings]
    TotalSupply = "20000000000000000000000000000" #20BILERD
    MinimumInflation = 0.0
    MaximumInflation = 0.1 #fraction of value 1 - 10%

[RewardsSettings]
    LeaderPercentage = 0.10 #fraction of value 1 - 10%
    DeveloperPercentage = 0.30 #fraction of value 1 - 30%
    DenominationCoefficientForView = "0.000000000000000001" #10^-18

[FeeSettings]
    MaxGasLimitPerBlock = "1500000000"
    MinGasPrice = "100000000000000" #will yield min tx fee of 10ERD
    MinGasLimit = "50000"
    GasPerDataByte = "1500"
    DataLimitForBaseCalc = "10000"

[ValidatorSettings]
    GenesisNodePrice = "500000000000000000000000" #500000ERD
    UnBondPeriod = "100000"
    MinStepValue = "10000000000000000000000"
    TotalSupply = "20000000000000000000000000000" #20BIL ERD
    NumNodes = 1000
    AuctionEnableNonce = "100000000000"
    StakeEnableNonce = "100000000000"
    NumRoundsWithoutBleed = "100"
    MaximumPercentageToBleed = "0.5"
    BleedPercentagePerRound = "0.00001"
    UnJailValue = "1000"

[RatingSettings]
    StartRating = 500000
    MaxRating = 1000000
    MinRating = 1
    ProposerIncreaseRatingStep = 405
    ProposerDecreaseRatingStep = 810
    ValidatorIncreaseRatingStep = 81
    ValidatorDecreaseRatingStep = 162
    [[RatingSettings.SelectionChance]]
    MaxThreshold = 0
    ChancePercent = 5
    [[RatingSettings.SelectionChance]]
    MaxThreshold = 100000
    ChancePercent = 0
    [[RatingSettings.SelectionChance]]
    MaxThreshold = 200000
    ChancePercent = 16
    [[RatingSettings.SelectionChance]]
    MaxThreshold = 300000
    ChancePercent = 17
    [[RatingSettings.SelectionChance]]
    MaxThreshold = 400000
    ChancePercent = 18
    [[RatingSettings.SelectionChance]]
    MaxThreshold = 500000
    ChancePercent = 19
    [[RatingSettings.SelectionChance]]
    MaxThreshold = 600000
    ChancePercent = 20
    [[RatingSettings.SelectionChance]]
    MaxThreshold = 700000
    ChancePercent = 21
    [[RatingSettings.SelectionChance]]
    MaxThreshold = 800000
    ChancePercent = 22
    [[RatingSettings.SelectionChance]]
    MaxThreshold = 900000
    ChancePercent = 23
    [[RatingSettings.SelectionChance]]
    MaxThreshold = 1000000
    ChancePercent = 24
