#Econimics config of the node
[EconomicsAddresses]
    CommunityAddress = "1bedf9f1db526aa98eb61f251e6eb29df64c0a4d96261b6fe9d4df1bc2cf5420"
    BurnAddress = "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef"

[RewardsSettings]
    RewardsValue = "20000000000000000000" #20ERD
    CommunityPercentage = 0.10
    LeaderPercentage = 0.50
    BurnPercentage = 0.40
    DenominationCoefficientForView = "0.000000000000000001" #10^-18

[FeeSettings]
    MaxGasLimitPerBlock = "1500000000"
    MinGasPrice = "100000000000000" #will yield min tx fee of 10ERD
    MinGasLimit = "100000"
    GasPerDataByte = "1500"
    DataLimitForBaseCalc = "10000"

[ValidatorSettings]
    StakeValue = "500000000000000000000000" #500000ERD
    UnBoundPeriod = "100000"

[RatingSettings]
    StartRating = 500000
    MaxRating = 1000000
    MinRating = 1
    ProposerIncreaseRatingStep = 1929
    ProposerDecreaseRatingStep = 3858
    ValidatorIncreaseRatingStep = 31
    ValidatorDecreaseRatingStep = 61
    [[RatingSettings.Chance]]
    MaxThreshold = 100000
    ChancePercent = 0
    [[RatingSettings.Chance]]
    MaxThreshold = 200000
    ChancePercent = 80
    [[RatingSettings.Chance]]
    MaxThreshold = 300000
    ChancePercent = 85
    [[RatingSettings.Chance]]
    MaxThreshold = 400000
    ChancePercent = 90
    [[RatingSettings.Chance]]
    MaxThreshold = 500000
    ChancePercent = 95
    [[RatingSettings.Chance]]
    MaxThreshold = 600000
    ChancePercent = 100
    [[RatingSettings.Chance]]
    MaxThreshold = 700000
    ChancePercent = 105
    [[RatingSettings.Chance]]
    MaxThreshold = 800000
    ChancePercent = 110
    [[RatingSettings.Chance]]
    MaxThreshold = 900000
    ChancePercent = 115
    [[RatingSettings.Chance]]
    MaxThreshold = 1000000
    ChancePercent = 120
