#Econimics config of the node
[GlobalSettings]
    TotalSupply = "20000000000000000000000000000" #20BILERD
    MinimumInflation = 0.0
    MaximumInflation = 0.1 #fraction of value 1 - 10%

[RewardsSettings]
    LeaderPercentage = 0.10 #fraction of value 1 - 10%
    DeveloperPercentage = 0.30 #fraction of value 1 - 30%
    DenominationCoefficientForView = "0.000000000000000001" #10^-18

[FeeSettings]
    MaxGasLimitPerBlock = "1500000000"
    MinGasPrice = "100000000000000" #will yield min tx fee of 10ERD
    MinGasLimit = "100000"
    GasPerDataByte = "1500"
    DataLimitForBaseCalc = "10000"

[ValidatorSettings]
    GenesisNodePrice = "500000000000000000000000" #500000ERD
    UnBoundPeriod    = "100000"

[RatingSettings]
    StartRating = 500000
    MaxRating = 1000000
    MinRating = 1
    ProposerIncreaseRatingStep = 2
    ProposerDecreaseRatingStep = 4
    ValidatorIncreaseRatingStep = 1
    ValidatorDecreaseRatingStep = 2
