# Since we do not have yet any round based enable flag, this file contains an empty definition
# To add a new round activation flag, add beyond L9 a defintion like:

# [RoundActivations.Example]
#     Options = []
#     Round = 600

[RoundActivations]
