# ElasticSearchConnector defines settings related to ElasticSearch such as login information or URL
[ElasticSearchConnector]
    ## We do not recommend to activate this indexer on a validator node since
    #the node might loose rating (even facing penalties) due to the fact that
    #the indexer is called synchronously and might block due to external causes.
    #Strongly suggested to activate this on a regular observer node.
    Enabled           = false
    IndexerCacheSize  = 100
    URL               = "http://localhost:9200"
    UseKibana         = false
    Username          = ""
    Password          = ""
    # EnabledIndexes represents a slice of indexes that will be enabled for indexing. Full list is:
    # ["tps", "rating", "transactions", "blocks", "validators", "miniblocks", "rounds", "accounts", "accountshistory"]
    EnabledIndexes    = ["tps", "rating", "transactions", "blocks", "validators", "miniblocks", "rounds", "accounts", "accountshistory"]

# EventNotifierConnector defines settings needed to configure and launch the event notifier component
[EventNotifierConnector]
    # Enabled signals whether the driver is enabled or not
    Enabled = true

    # UseAuthorization signals the proxy to use authorization
    # Never run a production setup without authorization
    UseAuthorization = false

    # ProxyUrl is used to communicate with the subscriptions hub
    # The indexer instance will broadcast data using ProxyUrl
    ProxyUrl = "http://localhost:5000"

    #
    Username = ""

    #
    Password = ""
