# ElasticSearchConnector defines settings related to ElasticSearch such as login information or URL
[ElasticSearchConnector]
    Enabled          = false
    IndexerCacheSize = 100
    URL              = "http://localhost:9200"
    UseKibana        = false
    Username         = ""
    Password         = ""
