#Ratings configuration

# proposer-validator importanceRatio = 1 =>
#   50% rating increase from proposer and 50% rating increase from validator

# ProposerIncreaseRatingStep = 1/2 * (maxRating - startRating)/(nrTimesProposerPerHour * hoursToGetToMaxRating)
# ValidatorIncreaseRatingStep = 1/2 * (maxRating - startRating)/(nrTimeValidatorPerHour * hoursToGetToMaxRating)
# ProposerDecreaseRatingStep = -2 * ProposerIncreaseRatingStep
# ValidatorDecreaseRatingStep = -2 * ValidatorIncreaseRatingStep


[General]
    StartRating = 500000
    MaxRating = 1000000
    MinRating = 1
    SignedBlocksThreshold = 0.01
    SelectionChances = [
        { MaxThreshold = 0, ChancePercent = 5},
        { MaxThreshold = 100000,ChancePercent = 0},
        { MaxThreshold = 200000,ChancePercent = 16},
        { MaxThreshold = 300000,ChancePercent = 17},
        { MaxThreshold = 400000,ChancePercent = 18},
        { MaxThreshold = 500000,ChancePercent = 19},
        { MaxThreshold = 600000,ChancePercent = 20},
        { MaxThreshold = 700000,ChancePercent = 21},
        { MaxThreshold = 800000,ChancePercent = 22},
        { MaxThreshold = 900000,ChancePercent = 23},
        { MaxThreshold = 1000000,ChancePercent = 24},
    ]

[ShardChain.RatingSteps]
    ProposerIncreaseRatingStep = 2315
    ProposerDecreaseRatingStep = -9260
    ValidatorIncreaseRatingStep = 37
    ValidatorDecreaseRatingStep = -148
    ConsecutiveMissedBlocksPenalty = 1.10

[MetaChain.RatingSteps]
    ProposerIncreaseRatingStep = 2315
    ProposerDecreaseRatingStep = -9260
    ValidatorIncreaseRatingStep = 6
    ValidatorDecreaseRatingStep = -24
    ConsecutiveMissedBlocksPenalty = 1.10