[StakingSystemSCConfig]
    GenesisNodePrice = "2500000000000000000000" #2.5KERD
    MinStakeValue = "100000000000000000000" #100ERD
    UnBondPeriod = 40
    MinStepValue = "100000000000000000000"
    AuctionEnableNonce = 100000000000
    StakeEnableNonce = 0
    NumRoundsWithoutBleed = 100
    MaximumPercentageToBleed = 0.5
    BleedPercentagePerRound = 0.00001
    MaxNumberOfNodesForStake = 28
    NodesToSelectInAuction = 28
    UnJailValue = "2500000000000000000" #0.1% of genesis node price
    ActivateBLSPubKeyMessageVerification = false #TODO set to true before mainnet

[ESDTSystemSCConfig]
    BaseIssuingCost = "5000000000000000000000" #5000ERD
    OwnerAddress = "erd1932eft30w753xyvme8d49qejgkjc09n5e49w4mwdjtm0neld797su0dlxp"
    Disabled = false

[GovernanceSystemSCConfig]
	ProposalCost = "5000000000000000000000" #5000ERD
	NumNodes     = 500
	MinQuorum    = 400
	MinPassThreshold = 300
	MinVetoThreshold = 50
	Disabled     = false
