[StakingSystemSCConfig]
    GenesisNodePrice = "2500000000000000000000" #2.5K eGLD
    MinStakeValue = "100000000000000000000" #100 eGLD
    MinUnstakeTokensValue = "10000000000000000000" #10eGLD
    UnBondPeriod = 250
    MinStepValue = "100000000000000000000"
    StakeEnableEpoch = 2
    StakingV2Epoch = 4
    NumRoundsWithoutBleed = 100
    MaximumPercentageToBleed = 0.5
    BleedPercentagePerRound = 0.00001
    MaxNumberOfNodesForStake = 36
    NodesToSelectInAuction = 36
    UnJailValue = "2500000000000000000" #0.1% of genesis node price
    ActivateBLSPubKeyMessageVerification = false

[ESDTSystemSCConfig]
    BaseIssuingCost = "5000000000000000000" #5 eGLD
    OwnerAddress = "erd1fpkcgel4gcmh8zqqdt043yfcn5tyx8373kg6q2qmkxzu4dqamc0swts65c"
    EnabledEpoch = 2

[GovernanceSystemSCConfig]
    NumNodes           = 500
    ProposalCost       = "5000000000000000000" #5 eGLD
    ProposalCostV2     = "5000000000000000000" #5 eGLD
    MinQuorum          = 400
    MinQuorumV2        = "500000000000" # VotePower of 10*sqrt(NodePrice)
    MinPassThreshold   = 300
    MinPassThresholdV2 = "251000000000"
    MinVetoThreshold   = 50
    MinVetoThresholdV2 = "249000000000"
    EnabledEpoch       = 2
    EnabledEpochV2     = 2

[DelegationManagerSystemSCConfig]
    BaseIssuingCost = "5000000000000000000" #5 eGLD
    MinCreationDeposit = "2500000000000000000000" #2.5K eGLD
    EnabledEpoch = 2

[DelegationSystemSCConfig]
    MinStakeAmount = "10000000000000000000" #10 eGLD
    EnabledEpoch   = 2
    MinServiceFee  = 0
    MaxServiceFee  = 10000
