[StakingSystemSCConfig]
    GenesisNodePrice = "2500000000000000000000" #2.5K eGLD
    MinStakeValue = "100000000000000000000" #100 eGLD
    MinUnstakeTokensValue = "10000000000000000000" #10eGLD
    UnBondPeriod = 250
    MinStepValue = "100000000000000000000"
    StakeEnableEpoch = 1
    StakingV2Epoch = 1
    DoubleKeyProtectionEnableEpoch = 1
    NumRoundsWithoutBleed = 100
    MaximumPercentageToBleed = 0.5
    BleedPercentagePerRound = 0.00001
    MaxNumberOfNodesForStake = 36
    UnJailValue = "2500000000000000000" #0.1% of genesis node price
    ActivateBLSPubKeyMessageVerification = false

[ESDTSystemSCConfig]
    BaseIssuingCost = "5000000000000000000" #5 eGLD
    OwnerAddress = "erd1fpkcgel4gcmh8zqqdt043yfcn5tyx8373kg6q2qmkxzu4dqamc0swts65c"
    EnabledEpoch = 2

[GovernanceSystemSCConfig]
    ProposalCost = "5000000000000000000" #5 eGLD
    NumNodes     = 500
    MinQuorum    = 400
    MinPassThreshold = 300
    MinVetoThreshold = 50
    EnabledEpoch = 2

[DelegationManagerSystemSCConfig]
    BaseIssuingCost = "0" #0 eGLD
    MinCreationDeposit = "1250000000000000000000" #1.25K eGLD
    EnabledEpoch = 1

[DelegationSystemSCConfig]
    MinStakeAmount = "10000000000000000000" #10 eGLD
    EnabledEpoch   = 1
    MinServiceFee  = 0
    MaxServiceFee  = 10000
